### ISSUE TITLE
Peer dependency conflict

### ISSUE THREAD

**Issue by hiaselhans** [mikbry/material-ui-color#108]
**Describe the bug**

It seems like 0.4.9 updated the react dependency to ^17, but a peer dependency isn't ready yet:

https://github.com/jcoreio/material-ui-popup-state/blob/321c4fdf37001f607f8c1611d48fed4fad4757a6/package.json#L153

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: airg@undefined
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peer react@"^17.0.1" from material-ui-color@0.4.9
npm ERR!   node_modules/material-ui-color
npm ERR!     material-ui-color@"^0.4.9" from the root project
npm ERR!   2 more (@material-ui/core, react-dom)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0" from material-ui-popup-state@1.7.1
npm ERR! node_modules/material-ui-popup-state
npm ERR!   peer material-ui-popup-state@"^1.7.1" from material-ui-color@0.4.9
npm ERR!   node_modules/material-ui-color
npm ERR!     material-ui-color@"^0.4.9" from the root project
```

**To Reproduce**

1. update react to 17.0.1
2. update material-ui-color to 0.4.9

**Desktop (please complete the following information):**

linux

**Comment by msalahz** [comment]
I'm having the same issue, Any updates here?

**Comment by mikbry** [comment]
Thanks @hiaselhans & @msalahz! I just published v0.4.10 where I revert back peer dependencies.

**Comment by msalahz** [comment]
now I'm getting this error on CI build
./node_modules/material-ui-color/esm/index.js
Cannot find module: 'styled-components'. Make sure this package is installed.

**Comment by mikbry** [comment]
You need to add styled-components. I plan to remove this dependencyin the future

**Comment by hiaselhans** [comment]
thx @mikbry !
