### ISSUE TITLE
hsv gradient position is changed on slider drag

### ISSUE THREAD

**Issue by hiaselhans** [mikbry/material-ui-color#111]
**Describe the bug**

when a slider (color / alpha) is dragged and the curser moves into the hsv box, the hsv value is changed with the cursor position.

i suspect this ( `|| event.buttons` )to be the reason:
https://github.com/mikbry/material-ui-color/blob/99b673cc962f870ac3d0c38fdc9c66e5448cb4a5/src/components/ColorBox/HSVGradient.jsx#L165-L170

**To Reproduce**
1. Go to https://codesandbox.io/s/material-ui-color-qb4vm?file=/src/App.tsx
2. open colorpicker
3. click alpha or hue slider
4. move mouse in hsv box

**Expected behavior**

hsv dot should persist

**Comment by mikbry** [comment]
Thanks @hiaselhans I will check it and fix it

**Comment by mikbry** [comment]
fixed in v1
