### ISSUE TITLE
ColorInput onChange is not firing a Color but a string or an array of strings

### ISSUE THREAD

**Issue by SAKSHISONI** [mikbry/material-ui-color#164]
On Change event when I am manually trying to enter the HEX code string it's not working.

Here I am writing a piece of code as well with which I am getting this bug.
<ColorPicker
    id="accent_sec_color"
    name="accent_sec_color"
    onChange={(e) => {
        if (e.css) {
            setThemeSettings({
                ...themeSettings,
                accent_sec_color: e.css.backgroundColor
            })
        }
    }}
    value={(typeof themeSettings.accent_sec_color !== 'undefined') ? themeSettings.accent_sec_color : ''}                            
/>

**Expected behavior**
It should allow entering manual string by typing.

**Screenshots**
![image](https://user-images.githubusercontent.com/12390755/119827683-0b51df00-bf17-11eb-995a-aaf561563634.png)
Here HEX code getting replaced automatically to white when entering manually.

Thanks In advance

**Comment by Samuel-Beslogic** [comment]
The type of onChange is indeed wrong (see above PR), you can fix that yourself using [`patch-package`](https://www.npmjs.com/package/patch-package) in the mean time.

You'd still probably want to store the picker's value separately in the state though.

```js
<ColorPicker
  id="accent_sec_color"
  name="accent_sec_color"
  onChange={(e) => {
    setPickerValue(e)
    if (!e.css) return
    setThemeSettings({
      ...themeSettings,
      accent_sec_color: e.css.backgroundColor
    })
  }}
  value={pickerValue}
/>
```
