### ISSUE TITLE
V5 Support

### ISSUE THREAD

**Issue by Domino987** [mikbry/material-ui-color#166]
Is there support for the soon to be default v5 version of material-ui planned?

Currently, it breaks because `makeStyles` was moved from the `core` to the `styles` package.

Moving it to the `styles` package should not break anything, since `core` already requires the default theme and provider.

`import { makeStyles } from '@material-ui/core/styles';`
to
`import { makeStyles } from '@material-ui/styles';`

Thank you for this repo!!!

**Comment by helllamer** [comment]
v5 shim for webpack:
```
//import { ColorPicker } from 'material-ui-color';
import { ColorPicker } from "string-replace-loader?search=core/styles&replace=styles!./node_modules/material-ui-color/index.js"

<ColorPicker defaultValue="transparent"/>
```

**Comment by Samuel-Beslogic** [comment]
Using [react-app-rewired](https://www.npmjs.com/package/react-app-rewired)
```js
/* config-overrides.js */
module.exports = function override(config, env) {
  config.module.rules.push({
    test: /material-ui-color/,
    loader: 'string-replace-loader',
    options: {
      search: /core\/styles/i,
      replace: 'styles'
    }
  })
  return config
}
```

**Comment by Samuel-Beslogic** [comment]
Since v5.0.0-rc.0 this simple change won't be enough given that [`Renamed packages to @mui/* as part of rebranding the company`](https://github.com/mui-org/material-ui/releases/tag/v5.0.0-rc.0)

**Comment by jessejamesrich** [comment]
Any word on an update for this guy? It's pretty troublesome with V5 breaking entire pages.

**Comment by mikbry** [comment]
I try to figure out, as V5 changes is also breaking `material-ui-color` V4 version. Should I create 2 versions for each MUI ?

**Comment by jessejamesrich** [comment]
Oh I see. So like a MUIC V5 Compatible or something (MUIC 2 V5)? I think I understand what the issue is. For some reason, I thought the changes were made, but I assume then they broke V4?

**Comment by Domino987** [comment]
What I am doing for material-table-core is to have a next branch with the v5 version und the normal branch with V4. So the user can install either one with just appending @next during the install. This makes it easy for the users. And any changes of master can be merged into next to keep both branches up to date

**Comment by Domino987** [comment]
I am sorry. Where is what at?

**Comment by jessejamesrich** [comment]
Sorry. Sorry. I misread you comment.

**Comment by roborew** [comment]
Hi, looking to have this module working on mui-v5 as soon as possible. This issues is closed, but the module is still not ready for V5, didn't think it right to open another issue. 

I've pulled down the current master to review but there does appear to stil be a number of issues to address.

Tests are failing:
Test Suites: 2 failed, 5 passed, 7 total
Tests:       16 failed, 48 passed, 64 total
Snapshots:   4 passed, 4 total
Time:        14.843 s

Not too many, mostly down to small API changes that could be easily remedied.
[failing_tests.pdf](https://github.com/mikbry/material-ui-color/files/7499382/failing_tests.pdf)

Additionally https://github.com/jcoreio/material-ui-popup-state also has a version 2.0 branch to support V5 mui, which now makes sense to include.

Probably a good idea to follow the same approach and create 2.0 release for this module. And continue to maintain a stable release for v1 and v4 of mui in another branch from master.

@mikbry is anyone working on this?

**Comment by viclafouch** [comment]
This package (https://viclafouch.github.io/mui-color-input/) handles this problem, supports both React 17 / 18 and MUI V5
