### ISSUE TITLE
Bug: ColorPicker pop-up is stuck with black colour

### ISSUE THREAD

**Issue by fappaz** [mikbry/material-ui-color#70]
**Describe the bug**
ColorPicker pop-up doesn't let me pick any colour other than black.

**How to reproduce**
Access the docs demos (https://mikbry.github.io/material-ui-color/?path=/docs/components-colorpicker--basic#deferred) and try picking a colour. Note: all the demos are having the same issue, except the very first one.

![MaterialUiColorPickerIssue](https://user-images.githubusercontent.com/4013668/85087170-ddf1b100-b230-11ea-900c-623298aa7980.gif)

Alternatively, I can reproduce it by just adding PickColor to my react component, like this:
`<ColorPicker defaultValue="#987654"/>`

**System settings**
- Chrome Version 83.0.4103.97 (Official Build) (64-bit) for Windows 10

**Expected behaviour**
The component should be able to let me pick any colour.

**Comment by mikbry** [comment]
Thanks, you pointed a regression. I fix it ASAP.

**Comment by mikbry** [comment]
Also, it works using keys UpArrow DownArrow

**Comment by mikbry** [comment]
In fact it is not a regression. It is a special case when several ColorPickers are used in the same page. It works ok when you have only one ColorPicker in a page.

**Comment by mikbry** [comment]
Fixed in v0.4.4 : https://github.com/mikbry/material-ui-color/releases
