### ISSUE TITLE
ColorPicker support for not rendering textfield

### ISSUE THREAD

**Issue by ivnflpz** [mikbry/material-ui-color#72]
**Is your feature request related to a problem? Please describe.**
The ColorPicker component should support having the option to not render a text field. 

**Describe the solution you'd like**
Adding a simple prop to the ColorPicker component to decide whether the text field will be rendered.

**Describe alternatives you've considered**
The first alternative is composing a new component myself using the ColorButton wrapped around a MUI's IconButton and ColorBox to build this functionality. However this also requires keeping track of open/close state and a ref to detect clicks outside the popover. 

Other option I tried was hiding the textfield through CSS but that seems hacky and I'm not happy with it.

**Additional context**
I'm happy to implement this feature if needed.

**Comment by mikbry** [comment]
Thanks Ivan. If you want to implement this feature your are welcome. Create a PR I will review it ;-)

**Comment by mikbry** [comment]
I just published v0.4.5 containing your PR

**Comment by ivnflpz** [comment]
Awesome. Thanks for the fast turnaround.

**Comment by Worlaf** [comment]
Hi, I want to use this library with typescript, but `hideTextfield` property is missing in [index.d.ts](https://github.com/mikbry/material-ui-color/blob/2f9fe16807b524c5a73b06123816a0a640f3f54e/index.d.ts#L42) (as well as `disableAlpha` property). Not sure if it is matter of separate issue (at least, first mentioned property should be part of this task I suppose).

**Comment by mikbry** [comment]
A PR was made for hideTextfield: #74
For disableAlpha a new issue  / PR is needed
Holly cow I just see the problem: there is 2 index.d.ts, I made an issue #76
Need to fix it

**Comment by mikbry** [comment]
Release 0.4.6 Fix:
- wrong index.d.ts used
- add hideTextfield property
- add disableAlpha property
- Tested using [typescript-colorpicker](https://github.com/mikbry/typescript-colorpicker)
