### ISSUE TITLE
onChange is not triggered when I change the color in ColorBox

### ISSUE THREAD

**Issue by superdev0505** [mikbry/material-ui-color#80]
**Describe the bug**
In Colorbox the onChange event is not triggered 
When I put two Colorbox in one dialog I got same id issue. 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by mikbry** [comment]
What are the parameters you send to ColorBox ?

**Comment by superdev0505** [comment]
I used ColorBox like this.
`<ColorBox defaultValue={layer.idColor} onChange={(color) => fillColorChange(color)} />`

**Comment by mikbry** [comment]
Use 'value' instead of 'defaultValue' as you are using ColorBox as a controlled component with 'onChange'

**Comment by superdev0505** [comment]
Yes It is working. Thanks
