### ISSUE TITLE
ColorPicker support disable 'plain' textfield format

### ISSUE THREAD

**Issue by ethaqnix** [mikbry/material-ui-color#82]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I enter a color using textInput and it transform my value into a text color
example : I want to enter color `#000FFF`, after typing `#000`, input text will change to `black`.

**Describe the solution you'd like**

I would like a props inside ColorPicker that disabled color automatic renaming.

**Describe alternatives you've considered**
I think that we can add a condition regarding this line 

https://github.com/mikbry/material-ui-color/blob/89b09128f5f55bf05ca753bb7821c58492a6d6e6/src/helpers/colorTool.js#L384

otherwise, I can make a custom input and hiding default one. But I think this could be usefull.

**Comment by mikbry** [comment]
Thanks @ethaqnix I will add a bool property disableAutomaticColor to ColorPicker

**Comment by mikbry** [comment]
Available in v0.4.7
