### ISSUE TITLE
Color box on dark mode has some glitches

### ISSUE THREAD

**Issue by mihaibogdan** [mikbry/material-ui-color#83]
I love this package. It's perfect for someone who uses material-ui. This bug is just a small thing but quite annoying.

**Describe the bug**
<img width="333" alt="Screenshot 2020-10-15 at 16 18 41" src="https://user-images.githubusercontent.com/6225068/96131895-6c85ee80-0f02-11eb-9a56-1a15f42676c4.png">
The color slider and alpha slider seem transparent. They work, but kind of have opacity 0. This only happens on the dark palette of material-ui.

 - OS: macOS
 - Browser Chrome
 - Version 86

**Comment by mikbry** [comment]
Thanks @mihaibogdan, I will try to reproduce this bug

**Comment by mikbry** [comment]
I can't reproduce it. your sliders hue and transparency are not rendered ok.

![Screenshot 2021-01-11 at 15 13 35](https://user-images.githubusercontent.com/395718/104192905-c32a9800-541f-11eb-99fb-4e69d2fcf77f.png)

**Comment by mihaibogdan** [comment]
After digging a bit more I found out that my original assumption was wrong. This glitch didn't happen when using dark theme, but when using [nested theming](https://material-ui.com/styles/advanced/#theme-nesting) because material-ui generates classes with an identifier at the end (MuiSlider-track-109 instead of MuiSlider-track). This causes the css rules to fail.

I've opened a PR for this - #107

**Comment by mikbry** [comment]
Release v0.4.9 is available fixing this bug using your PR @mihaibogdan, thanks!
