### ISSUE TITLE
Can't make localisation to work (Typescript)

### ISSUE THREAD

**Issue by mihaibogdan** [mikbry/material-ui-color#84]
Hi guys,

Love your package but I'm having some issues to make the localisation to work. I don't quite get the example from the docs.
I've looked through the codebase and it seems that there is no translate prop on any component.

Can somebody help me with this?

Thanks!

**Comment by mikbry** [comment]
Hi @mihaibogdan. 

In this code there is an example which switch between french and english, starting at line 103:
https://github.com/mikbry/material-ui-color/blob/master/stories/ColorPicker.stories.js

And result here:
https://mikbry.github.io/material-ui-color/?path=/story/components-colorpicker--localization

If you want to add an another language to the example you are welcome.

**Comment by mihaibogdan** [comment]
Hm, okay.

I'm trying to import useTranslate and it seems it's not exported:

![image](https://user-images.githubusercontent.com/6225068/96228264-064ea980-0f9e-11eb-88a7-072c67f51ed3.png)

And this is the material-ui-color module:

![image](https://user-images.githubusercontent.com/6225068/96228777-ac021880-0f9e-11eb-97fd-04807510f682.png)

**Comment by mikbry** [comment]
Ok I see. It is a problem in src/index.d.ts not exporting useTranslate

**Comment by mikbry** [comment]
I fixed other problems for translation to work with Typescript. It will be available in next release
