### ISSUE TITLE
Using a single hex value when the component is controlled causes problems (Typescript)

### ISSUE THREAD

**Issue by danwit** [mikbry/material-ui-color#85]
**Describe the bug**
Using the full color object (Type `Color`) provided by `onChange` immediately resolves this issue but I want to only save the hex value and use this as `value` for ColorPicker, which is controlled in my case.
The `value` field excepts a single hex value and displays the correct color just fine. However, the text input for HEX cannot be changed manually and I cannot use the color slider. I can still pick any color and after that the color slider becomes usable aswell.
I tried working around this issue by providing the `Color` object myself with the hex value inserted but I was not able to construct the object in a clean way since `format` is dependend on `enum ColorFormat` which is not exported.

**To Reproduce**
1. Use the ColorPicker as a controlled component
2. Pick only the `Color.hex` from `onChange` and use this as `value`
3. Open the ColorPicker and try using the color slider or changing the HEX text field manually

**Expected behavior**
The color slider and HEX text field should work when using a hex color as `value`. If this is not working by design the `value` field should only accept a `Color` object.

**Screenshots**
![colorpickerissue](https://user-images.githubusercontent.com/1330413/97084065-aba7f400-1614-11eb-9f65-16398464c99f.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Google Chrome
 - Version 85

**Additional context**
Exporting `enum ColorFormat` would also help since I could construct the `Color` object on my end.

**Comment by mikbry** [comment]
Thanks @danwit Yes it is a strange behaviour, but it is correct as you have no tint. I will think how to work differently.

**Comment by mikbry** [comment]
@danwit you should use `#${value.hex}` as new value.
see my example here:
https://codesandbox.io/s/material-ui-color-picker-qvcg3?file=/src/App.tsx:872-890

**Comment by danwit** [comment]
That looks very promising! Tbh, I since moved to using a regular input field instead of material-ui-color. But now I'm definitely going to switch back to try this out. Thank you! :)
