### ISSUE TITLE
Colorbox cant handle palette and disableAlpha

### ISSUE THREAD

**Issue by PieFlo** [mikbry/material-ui-color#86]
**Describe the bug**
I cannot use the option to disable the alpha slider and the option to add a palette to the colorbox

**To Reproduce**

using 
`<Colorbox palette={paletteObj} disableAlpha>`
should already throw the error "translate is not a function"

**Expected behavior**
The palette is displayed while the alphaslider is not

**Comment by mikbry** [comment]
Thanks @PieFlo I will check this bug

**Comment by hiaselhans** [comment]
got stuck at this too.
Maybe a good point would be to mention in the docs that paletteObj shouldn't be an actual <ColorPalette> object...

other than that, thanks for the good work!

**Comment by hiaselhans** [comment]
i think this can be closed @mikbry

**Comment by hiaselhans** [comment]
@mikbry i discovered a very strange behaviour with this today:

in development everything seems to work fine, but on a production build it fails as it used to before 0.4.10...
Do you have an idea where this could come from?
