### ISSUE TITLE
Weird styles behavior

### ISSUE THREAD

**Issue by IlyasArinov** [mikbry/material-ui-color#88]
**Describe the bug**
At first, dragging color picker handle works smoothly, but as time passes, the color picker becomes more and more sluggish.

Potential reason: Whenever colors are changed, new styles are added in </head/><style data-styled="active" data-styled-version="5.1.1">

You can check it here:
https://codesandbox.io/s/material-ui-color-weird-behavior-ob0s9?file=/src/App.js

**Comment by mikbry** [comment]
Thanks @IlyasArinov I will investigate on it

**Comment by mikbry** [comment]
You should use a ThemeProvider, your ColorPicker lacks some styles.
see my sandbox here:
https://codesandbox.io/s/material-ui-color-picker-qvcg3?file=/src/App.tsx
