### ISSUE TITLE
bump version

### ISSUE THREAD

**Issue by hiaselhans** [mikbry/material-ui-color#95]
**Is your feature request related to a problem? Please describe.**

i'd like to use npm packages and still make use of the fix in #87 

**Describe the solution you'd like**

a version bump to 0.4.7 would help :)

**Comment by mikbry** [comment]
Yes I Work on returned bugs, I hope by the end of this week v0.4.7

**Comment by hiaselhans** [comment]
thx @mikbry !

if you need any assistance i have a little spare time to help..

**Comment by mikbry** [comment]
v0.4.7 is available
